name: vca
favicon: null
layout_spectrum: 0.8909096682909876
typography_spectrum: 0.24929
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#010103'
    - '#f90e1d'
    - '#888888'
    - '#fb76e5'
  brandStrength: 0.3125
  lightness: 0.8321130443364382
  saturation: 0.09616881492547691
  rhythmicContrast: 0.009764611953869462
purpose: []
